[bash] add fancy colors

diff --git a/core/bashrc b/core/bashrc
--- a/core/bashrc
+++ b/core/bashrc
@@ -8,10 +8,14 @@
 # apparently needed for rcp or scp or something
 [[ $- != *i* ]] && return
 
-shopt -u promptvars
-
-# this allows us to get away mostly with $var instead of "$var"
+# this allows us to get away (mostly) with $var instead of "$var"
 IFS=
+
+# Whether to use fancy colors.
+# This requires at least 256-color support from the terminal.
+GALE_FANCY=
+[[ $(tput colors 2> /dev/null) -ge 256 ]] \
+  && GALE_FANCY=1
 
 # FUNCTIONS & ALIASES
 # ==============================================================================
@@ -110,7 +114,7 @@ udeject() {
 }
 
 # daemonize (fork) a command
-f() { setsid -f -- "$@" &>/dev/null; }
+f() { setsid -f -- "$@" &> /dev/null; }
 # daemonize (fork) a command and exit
 fx() { f "$@" && exit; }
 
@@ -135,7 +139,15 @@ lspath() {
 #   Sorts and prints exported environment variables.
 #
 lsenv() {
-  env | sort
+  local sed_script
+  if [[ $GALE_FANCY ]]; then
+    sed_script=$'s/^/\033[38;5;245m/; s/=/=\033[0m/'
+  else
+    sed_script=$'s/^/\033[1m/; s/=/=\033[0m/'
+  fi
+  env \
+    | LC_ALL=C sort -t '=' -k 1 \
+    | sed "$sed_script"
 }
 
 # n3 [<option>...] [<path>]
@@ -159,8 +171,8 @@ GALE_FEATURES=
 GALE_ENABLE_NVM=
 
 # source local configuration from $XDG_CONFIG_HOME/gale/bashrc
-GALE_LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/gale/bashrc"
-[[ -s $GALE_LOCAL_CONFIG ]] && . "$GALE_LOCAL_CONFIG"
+gale_local_config="${XDG_CONFIG_HOME:-$HOME/.config}/gale/bashrc"
+[[ -s $gale_local_config ]] && . "$gale_local_config"
 
 # initialize nvm if installed
 if [[ $GALE_ENABLE_NVM ]] && [[ -d ~/.nvm ]]; then
@@ -170,31 +182,58 @@ if [[ $GALE_ENABLE_NVM ]] && [[ -d ~/.nvm ]]; then
   source "$NVM_DIR/bash_completion"
 fi
 
-# autodetect nnn
-if [[ $NNNLVL ]]; then
-  GALE_NNN_PROMPT="\[\e[35m\]nnn($NNNLVL) "
+# BANNER
+# ==============================================================================
+
+printf '\033[0;7m  Bash %s | Powered by Gale  \033[0m\n' "$BASH_VERSION"
+if [[ $GALE_FANCY ]]; then
+  printf '\033[38;5;248mSystem:\033[0m %s\n' "$(uname -srm)"
+  printf '\033[38;5;248mTerminal:\033[0m %s \033[38;5;248m(fancy)\033[0m\n' "${TERM:-unknown}"
 else
-  GALE_NNN_PROMPT=
+  printf 'System: %s\n' "$(uname -srm)"
+  printf 'Terminal: %s\n' "${TERM:-unknown}"
 fi
 
-printf 'Bash version %s\n' "$BASH_VERSION"
-printf '\033[1mPowered by Gale\033[0m%s\n' "$GALE_FEATURES"
+# PROMPT
+# ==============================================================================
 
-# this sets PS1
-gale_prepare_prompt() {
+# if the last command exited unsuccessfully, show the exit code
+gale_show_excode() {
   local excode="$?"
-  PS1='\[\e[0m\e[1m\]'
-  PS1+=$GALE_NNN_PROMPT
-  PS1+='\[\e[31m\]\u@\h \[\e[34m\]\w'
-
   if [[ $excode -gt 0 ]]; then
-    PS1+=' \[\e[33m\]#'
-    PS1+=$excode
+    if [[ $GALE_FANCY ]]; then
+      printf >&2 '\e[0;38;5;203;48;5;88m exit %s \e[0m\n' "$excode"
+    else
+      printf >&2 '\e[0;31m[exit %s]\e[0m\n' "$excode"
+    fi
   fi
-
-  PS1+=' \[\e[0m\]\$ '
 }
 
-PROMPT_COMMAND=(gale_prepare_prompt)
+# update the terminal title
+gale_update_title() {
+  printf '\033]2;%s\007' "${USER}@${HOSTNAME%%.*} ${PWD/#$HOME/\~}"
+}
+
+PS1=
+PS1+='\[\e[0;1m\]'
+
+# autodetect nnn
+if [[ $NNNLVL ]]; then
+  if [[ $GALE_FANCY ]]; then
+    PS1+='\[\e[37;45m\] nnn($NNNLVL) '
+  else
+    PS1+='\[\e[35m\]nnn($NNNLVL) '
+  fi
+fi
+
+if [[ $GALE_FANCY ]]; then
+  PS1+='\[\e[37;48;5;196m\] \u@\h '
+  PS1+='\[\e[48;5;124m\] \w '
+  PS1+='\[\e[22;38;5;203;48;5;88m\]\$\[\e[0m\] '
+else
+  PS1+='\[\e[31m\]\u@\h \[\e[34m\]\w \[\e[0m\]\$ '
+fi
+
+PROMPT_COMMAND=(gale_show_excode gale_update_title)
 
 # vim:ft=bash
