Improve lesskey

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -24,8 +24,9 @@ if [[ -f ~/.config/gale/bashrc ]]; then
   . ~/.config/gale/bashrc
 fi
 
-__gale_echo() { command printf '%s\n' "$1"; }
-__gale_diag() { command printf >&2 '%s\n' "$1"; }
+__gale_echo() { command printf '%s\n' "${1-}"; }
+__gale_print() { command printf '%s' "$1"; }
+__gale_diag() { command printf >&2 '%s\n' "${1-}"; }
 __gale_warn() { command printf >&2 'warning: %s\n' "$1"; }
 __gale_err() { command printf >&2 'error: %s\n' "$1"; }
 
@@ -46,6 +47,24 @@ if __gale_dircolors=$(dircolors 2>/dev/null); then
   eval "$__gale_dircolors"
 fi
 unset __gale_dircolors
+
+#=============================================================================
+# MENU
+#=============================================================================
+
+gale_menu() {
+  local key
+  printf '\033[1mMenu:\033[0m [q] abort [s] sleep '
+  read -rsN1 key
+  printf '\r\033[K'
+  case $key in
+    s)
+      gale-sleep
+      ;;
+  esac
+}
+
+bind -x '"\C-o": gale_menu'
 
 #=============================================================================
 # FUNCTIONS & ALIASES
