bash changes & others

diff --git a/bash/init b/bash/init
--- a/bash/init
+++ b/bash/init
@@ -7,6 +7,8 @@
 
 gale_echo() { printf '%s\n' "$1"; }
 gale_diag() { printf >&2 '%s\n' "$1"; }
+gale_warn() { printf >&2 'warning: %s\n' "$1"; }
+gale_err() { printf >&2 'error: %s\n' "$1"; }
 
 if [[ -z $GALE_COLORS ]]; then
   # autodetect number of colors using tput
@@ -29,6 +31,7 @@ alias pacman='pacman --color=auto'
 
 alias sysleep='systemctl suspend'
 alias userctl='systemctl --user'
+alias md='mkdir -pv'
 
 # display the function's arguments
 argv() {
@@ -36,6 +39,10 @@ argv() {
   if [[ $# -gt 0 ]]; then
     printf '%q\n' "$@"
   fi
+}
+
+fork() {
+  "$@" <&- &>/dev/null & disown
 }
 
 # BLOCK DEVICES
@@ -62,16 +69,21 @@ cdnew() {
   fi
 }
 
-_resolve_source() {
+gale_resolve_block_device() {
   case $1 in
-    LABEL=*)
-      _DEVICE="/dev/disk/by-label/${1#LABEL=}" ;;
-    PARTLABEL=*)
-      _DEVICE="/dev/disk/by-partlabel/${1#PARTLABEL=}" ;;
+    l=*)
+      gale_echo "/dev/disk/by-label/${1#*=}"
+      ;;
+    pl=*)
+      gale_echo "/dev/disk/by-partlabel/${1#*=}"
+      ;;
     /*)
-      _DEVICE="$1" ;;
+      gale_echo "$1"
+      ;;
     *)
-      _DEVICE="/dev/$1" ;;
+      gale_err "invalid block device: $1"
+      return 1
+      ;;
   esac
 }
 
@@ -80,12 +92,13 @@ _resolve_source() {
 #   Mount <source> with udisksctl.
 #
 udmount() {
+  local source
   if [[ $# -ne 1 ]]; then
     gale_diag 'usage: udmount <source>'
     return 1
   fi
-  _resolve_source "$1"
-  udisksctl mount -b "$_DEVICE"
+  source=$(gale_resolve_block_device "$1") || return
+  udisksctl mount -b "$source"
 }
 
 # udumount <source>
@@ -93,22 +106,13 @@ udmount() {
 #   Unmount <source> with udisksctl.
 #
 udumount() {
+  local source
   if [[ $# -ne 1 ]]; then
     gale_diag 'usage: udeject <source>'
     return 1
   fi
-  _resolve_source "$1"
-  udisksctl unmount -b "$_DEVICE"
-}
-
-# fork a command
-f() {
-  nohup -- "$@" <&- &>/dev/null &
-}
-
-# fork a command and exit
-fx() {
-  nohup -- "$@" <&- &>/dev/null & exit
+  source=$(gale_resolve_block_device "$1") || return
+  udisksctl unmount -b "$source"
 }
 
 # lspath
@@ -133,8 +137,8 @@ lspath() {
 #
 lsenv() {
   env \
-    | LC_ALL=C sort -t '=' -k 1 \
-    | sed $'s/^/\033[1m/; s/=/=\033[0m/'
+      | LC_ALL=C sort -t '=' -k 1 \
+      | sed $'s/^/\033[1m/; s/=/=\033[0m/'
 }
 
 # cdn3 [<option>...] [<path>]
@@ -146,7 +150,7 @@ cdn3() {
   tmpfile=$(mktemp /tmp/n3.XXXXX)
   NNN_TMPFILE=$tmpfile command n3 "$@"
   excode=$?
-  [[ -f "$tmpfile" ]] && . "$tmpfile"
+  [[ -f $tmpfile ]] && . "$tmpfile"
   rm -f "$tmpfile"
   return "$excode"
 }
@@ -162,10 +166,27 @@ cdn3() {
   elif [[ -e /usr/lib/os-release ]]; then
     . /usr/lib/os-release
   fi
-  printf '\n'
-  printf '  \033[1mSystem:\033[0m   %s\n' "$(uname -srm)${PRETTY_NAME:+ % $PRETTY_NAME}"
-  printf '  \033[1mTerminal:\033[0m %s\n' "$TERM ($GALE_COLORS colors)"
-  printf '\n'
+
+  tbold=$'\033[1m'
+  treset=$'\033[0m'
+
+  printf -v time '%(%a %Y %b %d %I:%M %p)T'
+  printf -v hour '%(%k)T'
+  if [[ $hour -lt 5 ]]; then
+    timedesc=evening
+  elif [[ $hour -lt 12 ]]; then
+    timedesc=morning
+  elif [[ $hour -lt 18 ]]; then
+    timedesc=afternoon
+  else
+    timedesc=evening
+  fi
+
+  gale_echo
+  gale_echo "  ${tbold}System:${treset} $(uname -srm)${PRETTY_NAME:+ ($PRETTY_NAME)}"
+  gale_echo "  ${tbold}Terminal:${treset} ${TERM:-(unknown)} ($GALE_COLORS colors)"
+  gale_echo "  ${tbold}Time:${treset} $time. Good $timedesc."
+  gale_echo
 )
 
 # PROMPT
@@ -173,12 +194,13 @@ cdn3() {
 
 # if the last command exited unsuccessfully, show the exit code
 gale_show_excode() {
-  local excode="$?"
-  if [[ $excode -gt 0 ]]; then
+  local code="$?"
+  local esc=$'\033'
+  if [[ $code -gt 0 ]]; then
     if [[ $GALE_COLORS -ge 256 ]]; then
-      printf >&2 '\033[0;38;5;203;48;5;88m exit %s \033[0m\n' "$excode"
+      gale_echo "$esc[0;38;5;203;48;5;88m exit $code $esc[0m"
     else
-      printf >&2 '\033[0;31m[exit %s]\033[0m\n' "$excode"
+      gale_echo "$esc[0;31m[exit $code]$esc[0m"
     fi
   fi
 }
